run:
  timeout: 5m

linters:
  enable:
    - govet  
    - errcheck  
    - staticcheck 
    - unused    
    - gosimple    

issues:
  exclude-use-default: false
  exclude-dirs:
    - migrations
    - internal/api
  max-same-issues: 3 

output:
  formats: colored-line-number 